services:
  mealie:
    image: ghcr.io/mealie-recipes/mealie:latest # 
    container_name: mealie
    restart: always
    # ports:
    #     - "9925:9000" # 
    deploy:
      resources:
        limits:
          memory: 1000M # 
    volumes:
      - ./data:/app/data/
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mealie.entrypoints=https-internal"
      - "traefik.http.routers.mealie.rule=Host(`mealie.${DOMAIN_BASE_01}`)"
      - "traefik.http.routers.mealie.tls=true"
      - "traefik.http.routers.mealie.tls.certresolver=production"
      # - "traefik.http.routers.mealie.middlewares=forwardAuth-authentik@file"
      - "traefik.http.services.mealie.loadbalancer.server.port=9000"
      - "traefik.docker.network=management"
    environment:
      # Set Backend ENV Variables Here
      ALLOW_SIGNUP: "false"
      PUID: 1000
      PGID: 1000
      TZ: America/Chicago
      BASE_URL: https://mealie.${DOMAIN_BASE_01}
      LOG_LEVEL: DEBUG
      # Database Settings
      DB_ENGINE: postgres
      POSTGRES_USER: mealie
      POSTGRES_PASSWORD: ${MEALIE_POSTGRES_PASSWORD}
      POSTGRES_SERVER: mealie_postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: mealie
      SMTP_HOST: ${MEALIE_SMTP_HOST}
      SMTP_PORT: ${MEALIE_SMTP_PORT}
      SMTP_FROM_NAME: Mealie
      SMTP_AUTH_STRATEGY: TLS
      SMTP_FROM_EMAIL: ${MEALIE_SMTP_FROM_EMAIL}
      SMTP_USER: ${MEALIE_SMTP_USER}
      SMTP_PASSWORD: ${MEALIE_SMTP_PASSWORD}
      OIDC_AUTH_ENABLED: false
      OIDC_PROVIDER_NAME: authentik
      OIDC_CONFIGURATION_URL: http://authentik-server:9000/application/o/mealie/.well-known/openid-configuration
      OIDC_REDIRECT_URI: https://authentik.${DOMAIN_BASE_01}
      OIDC_CLIENT_ID: ${MEALIE_OIDC_CLIENT_ID}
      OIDC_CLIENT_SECRET: ${MEALIE_OIDC_CLIENT_SECRET}
      OIDC_SIGNUP_ENABLED: false
      OIDC_USER_GROUP: mealie-users
      OIDC_ADMIN_GROUP: mealie-admins
      OIDC_AUTO_REDIRECT: false   # Optional: The login page will be bypassed and you will be sent directly to your Identity Provider.
      OIDC_REMEMBER_ME: true     # Optional: By setting this value to true, a session will be extended as if "Remember Me" was checked.
    depends_on:
      mealie_postgres:
        condition: service_healthy
    networks:
      - management
      - mealie_backend
      - oidc

  mealie_postgres:
    container_name: mealie_postgres
    image: postgres:17
    restart: always
    volumes:
      - ./postgresql:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${MEALIE_POSTGRES_PASSWORD}
      POSTGRES_USER: mealie
      PGUSER: mealie
      POSTGRES_DB: mealie
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 30s
      timeout: 20s
      retries: 3
    networks:
      - mealie_backend

networks:
  management:
    external: true
  mealie_backend:
    external: true
  oidc:
    external: true

