# Building basic ingress stack for Docker Swarm cluster
# comments out container_name as is unsupported in Swarm Mode
# adds deploy: section

services:
  nginx-proxy-manager:
    image: 'jc21/nginx-proxy-manager:latest'
    # container_name: nginx-proxy-manager
    # restart: unless-stopped
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.role == manager
    ports:
      # These ports are in format <host-port>:<container-port>
      - '80:80' # Public HTTP Port
      - '443:443' # Public HTTPS Port
      - '81:81' # Admin Web Port
      - '50300:50300' # slskd tcp stream
      # Add any other Stream port you want to expose
      # - '21:21' # FTP

    #environment:
      # Uncomment this if you want to change the location of
      # the SQLite DB file within the container
      # DB_SQLITE_FILE: "/data/database.sqlite"

      # Uncomment this if IPv6 is not enabled on your host
      # DISABLE_IPV6: 'true'

    volumes:
      - ./nginx-proxy-manager/data:/data
      - ./nginx-proxy-manager/letsencrypt:/etc/letsencrypt
    networks:
      - proxy
  tunnel:
    image: cloudflare/cloudflared
    # restart: unless-stopped
    command: tunnel run
    # labels:
    # #   - "com.centurylinklabs.watchtower.enable=true"
    # #   - "com.centurylinklabs.watchtower.scope=monitor"  
    #   - "wud.watch=true"
    #   - "wud.trigger.include=discord.batch,docker.manual"  
    environment:
      - TUNNEL_TOKEN=${CLOUDFLARED_TUNNEL_TOKEN_02}
    networks:
      - proxy

networks:
  proxy:
    external: true